### ISSUE TITLE
The input size of InceptionResnetV1

### ISSUE THREAD

**Issue by chaochen95** [timesler/facenet-pytorch#2]
Thanks for your great work，when I run your code, I find something wrong, the output size of MTCNN is 160 * 160 and put this image to InceptionResnetV1, it wil return a RuntimeError said Output size is too small at x = self.avgpool_1a(x) in inception_resnet_v1.py line 270, so I changed the output size of MTCNN to 299 * 299，it works. 
I want to know if I am doing the right thing or there are another way to fix this.

**Comment by timesler** [comment]
Firstly, thanks for your interest in the project!

Could you let me know what versions of python, pytorch and torchvision you are running so I can try and reproduce the issue?

Were you running the example code from the repo and using the test images, or your own images?

**Comment by timesler** [comment]
@chaochen95 I've replaced the AvgPool2d layer in the InceptionResnetV1 class with an AdaptiveAvgPool2d layer. This should be robust to input size and will ensure that the model works with most image sizes (for very small images sizes, e.g. 32x32, the model will still fail on the earlier conv layers, but I think that is desired behaviour). 

It seems that AvgPool2d is happy when the input dimension is smaller than the pooling kernel, but not in all versions of pytorch.

If your issue isn't fixed in current master, let me know here.
