### ISSUE TITLE
Facial landmark?

### ISSUE THREAD

**Issue by YoWhatever** [timesler/facenet-pytorch#33]
Does this project support facial landmark detection?
I see word "align" in your file, but I don't find the relevant code.

**Comment by timesler** [comment]
No, there is no facial landmark detection in this repo. All references to alignment should have been removed some time ago - where did you see "align"? The reason the word is used at all is because it is used throughout the original [facenet repo](https://github.com/davidsandberg/facenet), despite not actually being alignment.

**Comment by timesler** [comment]
This functionality is now implemented via the detect method of the MTCNN class.
