### ISSUE TITLE
Why is the architecture different from the original paper?

### ISSUE THREAD

**Issue by zoujx96** [timesler/facenet-pytorch#88]
The original paper has the embedding as 128 dimension but here it's 512. The channel size of last feature map in original paper is 1024 but here it's 1792.

**Comment by timesler** [comment]
This repo was based upon the tensorflow repo by [David Sandberg](https://github.com/davidsandberg/facenet), rather than the original paper. The architecture is different because improved performance was achieved using a larger feature vector. See [here](https://github.com/davidsandberg/facenet/wiki/Training-using-the-VGGFace2-dataset) for a description of the changes made to the model and its training.
